trigger:
 - main

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: Pre-Requisites
    jobs:
      - job: Pre-Requisites
        steps:
          - script: new-packerServicePrincipal.ps1
            displayName: 'Install the pre-requisites'

  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo "Building the application"
            displayName: 'Build the application'

  - stage: Test
    jobs:
      - job: Test
        steps:
          - script: echo "Testing the application"
            displayName: 'Test the application'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: echo "Deploying the application"
            displayName: 'Deploy the application'
  
  - stage: Post-Deployment
    jobs:
      - job: Post-Deployment
        steps:
          - script: echo "Post-Deployment steps"
            displayName: 'Post-Deployment steps'