trigger:
 - main

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: Pre_Requisites
    jobs:
      - job: Pre_Requisites
        steps:
        
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'DevOpsConnection'
              scriptType: 'pscore'
              scriptLocation: 'scriptPath'
              scriptPath: './new-packerServicePrincipal.ps1'

  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo "Building the application"
            displayName: 'Build the application'

  - stage: Test
    jobs:
      - job: Test
        steps:
          - script: echo "Testing the application"
            displayName: 'Test the application'

  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - script: echo "Deploying the application"
            displayName: 'Deploy the application'
  
  - stage: Post_Deployment
    jobs:
      - job: Post_Deployment
        steps:
          - script: echo "Post-Deployment steps"
            displayName: 'Post-Deployment steps'